application:
  version: @project.version@
spring:
  profiles:
    active: dev
#    active: prod
  datasource:
    url: jdbc:postgresql://188.227.18.141:5432/usersvk_db
    username: blank
    password: blank
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
vkontakte:
  clientId: blank
  clientCode: blank
  callbackUri: http://188.227.18.141:8080/callback
  scope: wall,offline,email