application:
  version: @project.version@
spring:
  profiles:
    active: dev
#    active: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
vkontakte:
  clientId: blank
  clientCode: blank
  callbackUri: http://188.227.18.141:8080/callback
  scope: wall,offline,email