spring:
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://188.227.18.141:5432/usersvk_db_dev
    username: blank
    password: blank
    driver-class-name: org.postgresql.Driver